### ISSUE TITLE
Many Server Sent Events in parallel cause requests to hang

### ISSUE THREAD

**Issue by ahtcx** [apple/swift-openapi-generator#504] opened 2024-01-12 05:52 UTC
### Question

Thanks for the great library, it's been a joy to use so far! I've previously been using [EventSource](https://github.com/inaka/EventSource) for their SSE implementation but saw you recently released SSE support so I have attempted to migrate to using that.

My SwiftUI app displays a list and then fires off the SSE request for each of the list items. This uses the view `.task` modifier. The first list item gets a response immediately but unfortunately the next ones don't. The generated client calls end up hanging for a while, often a few seconds. I tried looking into `SessionURLTransport` to see if there was anything obvious but I'm quite new with Swift and it was a bit overwhelming.

Interestingly once those call start hanging, it also means every other endpoint using the generated client starts to hang too, not just the SSE calls.

Thanks!

**Comment by czechboy0** [comment] 2024-01-12 07:35
Can you share a snippet of the code that calls the generated client? We'll need a bit more details here to be able to narrow down what's happening.

You could also write a ClientMiddleware for logging to see what requests are being sent, and what responses are coming back, to aid debugging.

**Comment by czechboy0** [comment] 2024-01-12 08:49
Also, out of curiosity, can you try if you reproduce the same issue with https://github.com/swift-server/swift-openapi-async-http-client

**Comment by ahtcx** [comment] 2024-01-12 11:42
It works as expected using the `AsyncHTTPClientTransport`, the requests happen instantly. 

The code method I have looks a bit like this:

```swift
extension Fetchable_Value_Manager where Value == Components.Schemas.Board_Contents {
  static var board_contents: Fetchable_Value_Manager { .init() }

  @MainActor
  func stream(_ api: API, _ options: Operations.board_stream_contents.Input) async {
    withAnimation { state.to_fetching() }

    do {
      let response = try await api.client.board_stream_contents(options)

      switch response {
      case .unauthorized:
        throw API_Error.unauthorized()
      case .undocumented:
        throw API_Error.undocumented
      case let .ok(response):
        let board_contents_message_event_stream = try response.body.text_event_hyphen_stream
          .asDecodedServerSentEventsWithJSONData(of: Components.Schemas.Board_Contents.self)

        for try await board_contents_message_event in board_contents_message_event_stream {
          if let board_contents = board_contents_message_event.data {
            withAnimation { state.to_fetched(board_contents) }
          }
        }
      }
    } catch {
      withAnimation { state.to_failed(error) }
    }
  }
}
```

I gets run in code that works a bit similar to this:

```swift
List {
  ForEach(boards) { board in
    Board_View(board).task { await board_contents(api, .init(query: .init(board_id: board.id))) }
  }
}
```

I'll try get a full reproduction repo set up this weekend when I have a bit more time to do so.

Thanks!

**Comment by czechboy0** [comment] 2024-01-12 14:30
> I'll try get a full reproduction repo set up this weekend when I have a bit more time to do so.

That'd be great, should make debugging this much easier, thank you.

**Comment by simonjbeaumont** [comment] 2024-01-13 06:49
> It works as expected using the AsyncHTTPClientTransport, the requests happen instantly.

It will be interesting to see if we can get a network trace for this too. If it works using AHC, it could be buffering in URLSession somewhere before delivering to the delegate within the URLSessionTransport.

**Comment by ahtcx** [comment] 2024-01-15 11:49
@czechboy0 I've updated the iOS example project to replicate the issue here: https://github.com/ahtcx/swift-openapi-generator/commit/a88e2c6d730e137da71fabfbe33eec627e20d74f

**Comment by czechboy0** [comment] 2024-01-15 13:41
@ahtcx Which server is the example hitting?

**Comment by ahtcx** [comment] 2024-01-15 20:57
> @ahtcx Which server is the example hitting?

@czechboy0 It's using the one in `/Examples/event-streams-server-example`

**Comment by czechboy0** [comment] 2024-01-16 09:25
Hi @ahtcx, so @simonjbeaumont and myself investigated this more closely.

1. The AHC and URLSession transports behave the same way, we couldn't find a scenario in which they differed. So at least from what we've seen so far, there doesn't seem to be an issue in the URLSession transport.
2. The code you provided likely doesn't do what you want because the state and the views are intertwined in a way where the view triggers a task, the task fetches some data and sets a `@State` property, which in turn invalidates the state, which restarts/cancels the task. To address this one, I recommend looking more at SwiftUI documentation and WWDC talks around state management, for example you could move all the networking into a type that conforms to `ObservableObject`, which vends the current values to all the views, and uses `@Published` properties to notify its observees of it being changed. The important part is that the state/network stream should be owned by that object, not by the views (which you have today in the example).

Closing this issue for now - if you find more information that still points to an issue in the URLSession transport, please add more comments and we can reopen if needed.

**Closed by czechboy0** 2024-01-16 09:25 UTC
Labels: status/triage, kind/support

**Comment by ahtcx** [comment] 2024-01-16 11:13
Hey @czechboy0, thanks for having a look. It's very possible my code is faulty, I'm pretty new to Swift/SwiftUI haha so I'll dig around a bit more. Just in regards to your first point, are you saying you were unable to replicate the issue with the code I gave? Or that you were able to replicate the issue but that the issue doesn't stem from this project?

**Comment by czechboy0** [comment] 2024-01-16 11:15
We weren't able to replicate the issue of anything hanging, the app remained responsive the whole time. However we noticed that the cells weren't updating with the events coming from the server, which was caused by the task cancelation I described above.

**Comment by ahtcx** [comment] 2024-01-16 11:17
Odd, I guess maybe it's something specific to my setup or system somehow. Which iOS version were you using? I've had it happen on 17.0+.

**Comment by simonjbeaumont** [comment] 2024-01-16 13:28
> are you saying you were unable to replicate the issue with the code I gave?

Concretely, we took your branch (thank you very much for taking the time to prepare it!) and played around with the iOS app with the local SSE server and saw the same behaviour with both transports. Specifically, we didn't see any hanging requests, and each row would be populated with the first of the three events from the stream and never updated—and this behaviour was the same for both transports.

**Comment by simonjbeaumont** [comment] 2024-01-16 14:53
@ahtcx I took some extra time to play around some more and think I understand the difference you were seeing. On first launch, with the URLSession transport, the list seemed to take longer to populate and seemed to do so in chunks. Furthermore, when making big sweeping scrolls, you can see the list update in batches of ~6 per second (more on that to come) and so would take 2-3 seconds to fully populate the list. I can also see that with AHC transport everything just updated as you scrolled.

This turned out to be due to `URLSessionConfiguration. httpMaximumConnectionsPerHost `][^1].

The `URLSessionTransport` initializer accepts an optional `URLSession`  parameter, and uses `URLSession.shared` if not provided.

I found that the following code made the app behave in a similar way as when using the AHC transport:

```swift
var urlSessionConfiguration = URLSessionConfiguration.default
urlSessionConfiguration.httpMaximumConnectionsPerHost = 100
let urlSession = URLSession(configuration: urlSessionConfiguration)
let client = Client(transport: URLSessionTransport(configuration: .init(session: urlSession)))
// ...
```

Could you confirm that this is the problem you were seeing and that this resolves your symptom.

I will note that @czechboy0's observation on the structure of the app and SwiftUI code should probably be considered, but hopefully this clears up the observed differences between the two transport implementations?

[^1]:
    This property determines the maximum number of simultaneous connections made to each host by tasks within sessions based on this configuration.

    This limit is per session, so if you use multiple sessions, your app as a whole may exceed this limit. Additionally, depending on your connection to the Internet, a session may use a lower limit than the one you specify.

    The default value is 6.

    — https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1407597-httpmaximumconnectionsperhost

**Comment by ahtcx** [comment] 2024-01-16 15:28
Sorry about that, indeed the example I gave was buggy. I had tried to strip it down as much as possible for the replication but it ended up no longer reflecting how my actual app code which is properly using `ObservableObject`s and didn’t have any of task cancelling issues.

@simonjbeaumont Wow that was the issue, thank you so much - I really appreciate all of your guy's help and work into this amazing package! 🚀
