### ISSUE TITLE
Colon support in Path Parameters

### ISSUE THREAD

**Issue by AruneshRathore** [apple/swift-openapi-generator#499] opened 2023-12-27 13:51 UTC
### Question

We have a API like /{accounts}:lookUp.
in client.swift file accounts parameter is not created. Like any parameter before colon symbol is not created in client.swift file.
Please help in this issue as I am stuck there

**Comment by czechboy0** [comment] 2023-12-27 15:43
Can you share the operation snippet of the OpenAPI document?

**Comment by AruneshRathore** [comment] 2023-12-28 05:15
this is the code yaml file:

"/v1alpha/{integrationType}/{integrationId}/engagements/{engagementId}:join":
    post:
      tags:
        - Engagements
      summary: Join Engagement
      description: Joins an Engagement as an active participant.
      operationId: joinEngagement
      parameters:
        - $ref: "#/components/parameters/integrationType"
        - $ref: "#/components/parameters/integrationId"
        - $ref: "#/components/parameters/engagementId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JoinEngagement"
            examples:
              default:
                $ref: "#/components/examples/JoinEngagement"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Engagement"
              examples:
                "Join Engagement":
                  $ref: "#/components/examples/Engagement"


and auto generated code in Client.swift is:
public func joinEngagement(_ input: Operations.joinEngagement.Input) async throws -> Operations.joinEngagement.Output {
        try await client.send(
            input: input,
            forOperation: Operations.joinEngagement.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/v1alpha/{}/{}/engagements/{}/join",
                    parameters: [
                        input.path.integrationType,
                        input.path.integrationId,
                        input.path.engagementId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .none:
                    body = nil
                case let .json(value):
                    body = try converter.setOptionalRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.joinEngagement.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.Engagement.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))

**Comment by czechboy0** [comment] 2023-12-28 07:34
Can you also share the contents of `#/components/parameters/engagementId`?

**Comment by AruneshRathore** [comment] 2023-12-28 10:07
content type is GUID

**Comment by czechboy0** [comment] 2023-12-28 11:06
I meant if you could share the parameter definition

**Comment by AruneshRathore** [comment] 2023-12-28 11:59
We had created our client class and define this below function and inside that we are calling operations.joinEngagement which is a generated code and there are three parameters all of them are String type, as we are not getting engagementId in generated code and even if we pass engagementId from this method its still returns the bad request response and the reason is :Join due which it is not generating third parameter.


public func joinEngagament(_ engagamentID: String, forSessionID sessionID: String, andDialogID dialogID: String) async throws -> Bool {
        logger.debug("\(#function): SessionID: \(sessionID), \n engagamentID: \(engagamentID), \n and dialogID: \(dialogID)")
        
        let path = Operations.joinEngagement.Input.Path(integrationType: integrationType, integrationId: integrationID, engagementId: engagamentID)
        let body = Operations.joinEngagement.Input.Body.json(Components.Schemas.JoinEngagement(dialogId: dialogID, sessionId: sessionID))
        
        let response = try await client.joinEngagement(path: path, body: body)
        print(response)
        
        switch response {
        case .ok(_):
            logger.debug("Joined the engagement: dialogID: \(dialogID)")
            return true
        case .badRequest(_):
            throw AXPError.badRequest
        case .unauthorized(_):
            throw AXPError.notAuthorized
        case .forbidden(_):
            throw AXPError.notAuthorized
        case .notFound(_):
            throw AXPError.notFound
        case .internalServerError(_):
            throw AXPError.internalError
        case .serviceUnavailable(_):
            throw AXPError.serviceNotAvailable
        case .undocumented(statusCode: let statusCode, _):
            logger.error("Undocumented response: \(statusCode)")
            throw AXPError.undocumented
        }
    }

**Comment by czechboy0** [comment] 2023-12-28 15:09
Right, I suspect there's some issue with the parameter definition in the OpenAPI document. Can you share the parameter engagemenentId's definition in the OpenAPI doc? I suspect there's a problem there.

**Comment by AruneshRathore** [comment] 2023-12-29 05:14
engagementId:
      name: engagementId
      description: "The unique 36 character internal id that represents the engagement."
      required: true
      in: path
      schema:
        type: string
        minLength: 36
        maxLength: 36
        pattern: '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$'
        example: "8d7cf5b8-70ad-11eb-9439-0242ac130002"

**Comment by simonjbeaumont** [comment] 2023-12-29 08:52
> 3.2 Path Templating §
> 
> Path templating refers to the usage of template expressions, delimited by curly braces ({}), to mark a section of a URL path as replaceable using path parameters.
> 
> Each template expression in the path MUST correspond to a path parameter that is included in the Path Item itself and/or in each of the Path Item’s Operations.

IIUC partial path parameters, e.g. when one component/segment contains a mix of parameters and other characters, while possible, can result in ambiguous parsing and some tools even forbid them for this reason.  

A quick search for me brings up results indicating that Postman and AWS API Gateway don't support this. 

I can see that the use of a fixed length path parameter or strict regex, such as this UUID, allows for unambiguous parsing but this logic will be hard to generalise. 

@czechboy0 is this something we already attempt to support today?

**Comment by AruneshRathore** [comment] 2023-12-29 10:18
> > 3.2 Path Templating §
> > Path templating refers to the usage of template expressions, delimited by curly braces ({}), to mark a section of a URL path as replaceable using path parameters.
> > Each template expression in the path MUST correspond to a path parameter that is included in the Path Item itself and/or in each of the Path Item’s Operations.
> 
> IIUC partial path parameters, e.g. when one component/segment contains a mix of parameters and other characters, while possible, can result in ambiguous parsing and some tools even forbid them for this reason.
> 
> A quick search for me brings up results indicating that Postman and AWS API Gateway don't support this.
> 
> I can see that the use of a fixed length path parameter or strict regex, such as this UUID, allows for unambiguous parsing but this logic will be hard to generalise.
> 
> @czechboy0 is this something we already attempt to support today?

We had checked the API in postman and swagger and it is working fine and same yaml file has been used in Android side as well they are able to generate correct parameters.

<img width="833" alt="Screenshot 2023-12-29 at 3 44 41 PM" src="https://github.com/apple/swift-openapi-generator/assets/43928616/848091cf-55d6-40cf-b1f8-837dfa1541ba">

**Comment by czechboy0** [comment] 2023-12-29 10:51
Clients should support it, but Si is right, server code would probably not route this operation correctly due to the mixed component.

It's possible there's a bug in the generator here, I'll investigate next week.

**Comment by simonjbeaumont** [comment] 2023-12-31 20:25
(Somewhat related: #387)

**Comment by czechboy0** [comment] 2024-01-01 09:23
Yeah this was improved in #491, so we need to see why it's not working here.

**Comment by AruneshRathore** [comment] 2024-01-03 05:54
@czechboy0 the Main issue is the colon symbol at last(":join"), if I am removing colon and adding "/" then it is able to convert and all the parameters are there.

**Comment by rathore2314** [comment] 2024-01-03 11:40
@simonjbeaumont , @czechboy0  how much time will it take to fix this issue

**Comment by simonjbeaumont** [comment] 2024-01-03 12:20
I'm currently on vacation so won't get chance to look at this immediately. It needs a bit more investigation. @czechboy0 might get to it sooner.

**Comment by simonjbeaumont** [comment] 2024-01-04 08:33
@AruneshRathore can you confirm what behaviour you are seeing, please?

> Like any parameter before colon symbol is not created in client.swift file.

The following OpenAPI snippet does result in a generated parameter for `a`:

```yaml
"/a/{a}:join":
  get:
    parameters:
      - name: a
        in: path
        required: true
        schema:
          type: string
    operationId: joinA
    responses:
      default:
        description: Response
```

Here's an except from the generated code in `Types.swift` and `Client.swift`:

```swift
                public struct Input: Sendable, Hashable {
                    public struct Path: Sendable, Hashable {
                        public var a: Swift.String
                        public init(a: Swift.String) {
                            self.a = a
                        }
                    }
                    public var path: Operations.joinA.Input.Path
                    public init(path: Operations.joinA.Input.Path) {
                        self.path = path
                    }
                }
```

```swift

                { input in
                    let path = try converter.renderedPath(
                        template: "/a/{}:join",
                        parameters: [
                            input.path.a
                        ]
                    )
                    var request: HTTPTypes.HTTPRequest = .init(
                        soar_path: path,
                        method: .get
                    )
                    suppressMutabilityWarning(&request)
                    return (request, nil)
                }
```


> We had created our client class and define this below function and inside that we are calling operations.joinEngagement which is a generated code and there are three parameters all of them are String type, as we are not getting engagementId in generated code and even if we pass engagementId from this method its still returns the bad request response and the reason is :Join due which it is not generating third parameter.
> ```swift
>public func joinEngagament(_ engagamentID: String, forSessionID sessionID: String, andDialogID dialogID: String) async throws -> Bool {
>     logger.debug("(#function): SessionID: (sessionID), \n engagamentID: (engagamentID), \n and dialogID: (dialogID)")
>
>     let path = Operations.joinEngagement.Input.Path(integrationType: integrationType, integrationId: integrationID, engagementId: engagamentID)
>     let body = Operations.joinEngagement.Input.Body.json(Components.Schemas.JoinEngagement(dialogId: dialogID, sessionId: sessionID))
>
>     let response = try await client.joinEngagement(path: path, body: body)
>     ...

This code clearly _does_ have an `engagementID` parameter. The fact that it is of type string is expected as that is the type of the parameter in the OpenAPI document.

I think we'll need clarity on the following statement:

> even if we pass engagementId from this method its still returns the bad request response and the reason is :Join due which it is not generating third parameter.

**Comment by czechboy0** [comment] 2024-01-09 09:41
Hi @AruneshRathore - Si's test shows that at least in that example case, a mixed path component works correctly with the generated code. Please read Si's recommendations and if you have any follow-up questions, reply here and we can reopen the issue if needed.

**Comment by zjane-github** [comment] 2024-01-10 18:39
@czechboy0 and @simonjbeaumont 

> Specifically, what are you not seeing that you expect to? The client code seems to contain a Swift function parameter for the OpenAPI path parameter; are you saying this is resulting in a HTTP request with an incorrect path?

Yes. It did generate incorrect path

Here is the request that was captured by DataDog:

https://dev-20.ixcc-sandbox.avayacloud.com/sdk/v1alpha/messaging-integrations/0d129478-a6e6-4904-8267-f3897c704801/engagements/%7BengagementId%7D:join
As you can see: {engagementId} was not replaced by the real value in the Path

Here is the debug screenshot from Xcode at TransportMiddleware, which is also showing {engagamentId} is not replaced by the real value
<img width="1009" alt="Screenshot 2024-01-10 at 1 17 40 PM" src="https://github.com/apple/swift-openapi-generator/assets/54911748/546f5eb9-a343-4fc9-b3d2-5106e8dd4434">

Here is the screenshot from Xcode we set the Path before
<img width="1238" alt="Screenshot 2024-01-10 at 1 38 20 PM" src="https://github.com/apple/swift-openapi-generator/assets/54911748/7ca69726-af03-495e-bb7f-772d10cae896">

Please let us know if you have any more questions

**Comment by simonjbeaumont** [comment] 2024-01-10 19:42
So IIUC the generated _code_ does contain the parameter but it doesn't correctly propagate this parameter into the path used when making the HTTP request. 

If so, thanks for clearing that up, and that's something we can take a look into.

**Comment by zjane-github** [comment] 2024-01-10 20:20
@simonjbeaumont  Could you please reopen this case? Thanks!

**Comment by simonjbeaumont** [comment] 2024-01-10 22:03
> @simonjbeaumont  Could you please reopen this case? Thanks!

Of course, sorry for not doing that with my last reply. 

I'm OOO for the rest of this week so we I'm not able to investigate this further until next week. 

//cc @czechboy0

**Comment by czechboy0** [comment] 2024-01-10 22:23
Can you please attach the full OpenAPI document? Something that could help us actually reproduce it, thanks!

**Comment by zjane-github** [comment] 2024-01-11 16:35
Attached, is the OpenAPI document
[digital-chat-sdk.txt](https://github.com/apple/swift-openapi-generator/files/13905913/digital-chat-sdk.txt)

Replacing .txt to .yaml

**Comment by czechboy0** [comment] 2024-01-11 23:06
Thanks - I was able to confirm that this was fixed in 1.1.0 by https://github.com/apple/swift-openapi-generator/pull/491. So marking this as a duplicate and you should just need to update your dependencies to the latest and it should work.

**Closed by czechboy0** 2024-01-11 23:06 UTC
Labels: status/triage, kind/support

**Comment by zjane-github** [comment] 2024-01-12 15:21
@czechboy0  @simonjbeaumont  Thanks. This is to confirm that PR 491 fixed this issue. Much appreciated!

**Comment by simonjbeaumont** [comment] 2024-01-13 06:51
No problem, and happy your issue is resolved.

Next time, please do use the issue template, which includes the version of the packages used. This would have saved a lot of investigation on our end. 😊
