### ISSUE TITLE
Some weird behaviour after I update my mac to use swift 6

### ISSUE THREAD

**Issue by Dracks** [apple/swift-openapi-generator#676] opened 2024-11-17 20:57 UTC
### Question

Hello, 

I'm working on my pet project MrScrooge (which uses vapor and I'm using the openapi-generator to generate the apis), and last week I decided to upgrade my company laptop to the latest version of mac, which implied a migration of swift to 6. The package.json is not still changed (I'm awaiting to finish the lasts big things after involve myself on that) and I found some weird behaviour, which I don't know if everything is related to this project, but since the first simptom I think comes from the openapi generator, Let's start for here. 

The first simptom, it generates at some point (not allways) the build files that OpenApi generates to the root (Client.*, Types.* and Server.* files):
![image](https://github.com/user-attachments/assets/214acc7b-c4f9-48cd-bd90-7e0482cadb5a)

I don't know if I need to configure some specific stuff. You can see the branch in which I'm working here: https://github.com/Dracks/mr-scrooge/pull/30

Is it something that I missed to configure? 

Also, after this happens, (two or three compilations) swift decides to start throwing linking errors. (making impossible to compile again, until (not found any better way yet) full cleanup of the .build folder. 

I'm using zed as editor, and I compile (and test) mainly using terminal (I've got a small bash script to automatically launch build after some changes) 

Thanks, 
Dracks.

**Comment by simonjbeaumont** [comment] 2024-11-18 15:06
> The first simptom, it generates at some point (not allways) the build files that OpenApi generates to the root (Client._, Types._ and Server.* files):

This sounds very strange. The Swift OpenAPI Generator CLI invocation is made by SwiftPM when using the plugin and it should be passing an appropriate output directory based on the currently configured build directory.

How are you driving the build, or is that opaque to you (done by the editor or some editor plugin that drives SwiftPM)?

**Comment by dschaefer2** [comment] 2024-11-18 16:03
I still have yet and to see that but lots of people reporting it. I'm not sure how files can end up in the root, but it's clearly happening. A reproducible scenario that I could debug with would be a huge help.

**Comment by Dracks** [comment] 2024-11-18 16:17
Yes, (I think I'm driving the build) I simply run swift build, (tecnically I've got an small bash script to run the build, or the tests at any change in swift files) 

> I still have yet and to see that but lots of people reporting it. I'm not sure how files can end up in the root, but it's clearly happening. A reproducible scenario that I could debug with would be a huge help.

My intention is not to spam my project, but maybe you can try to clone my project the branch in which is happening?

**Comment by czechboy0** [comment] 2024-11-18 16:41
I suspect it has something to do with build plugins, almost seems like a race condition where sometimes the symbols path for the task that compiles the generated files ends up being (defaulted to?) the package path?

**Comment by dschaefer2** [comment] 2024-11-18 19:57
At any rate, we should move this to swift-package-manager. Any objections?

**Comment by simonjbeaumont** [comment] 2024-11-18 20:01
> At any rate, we should move this to swift-package-manager. Any objections?

Not from me.

**Comment by dschaefer2** [comment] 2024-11-18 20:04
Hrrmm, I can't since you guys are still in the apple org. At any rate, I'll dig up another one I have in this issue and link it.

**Comment by czechboy0** [comment] 2024-11-19 09:04
Thanks @dschaefer2, let's use https://github.com/swiftlang/swift-package-manager/issues/7930 to track this then. Closing.

**Closed by czechboy0** 2024-11-19 09:04 UTC
Labels: status/triage, kind/support
