### ISSUE TITLE
Generating client for GitHub API fails

### ISSUE THREAD

**Issue by heikowitte** [apple/swift-openapi-generator#186] opened 2023-08-10 09:07 UTC
Compiling a client for the GitHub API using the dereferenced version of the [API spec](https://github.com/github/rest-api-description/blob/main/descriptions/api.github.com/dereferenced/api.github.com.deref.yaml) fails with the following error:

```
Found neither a $ref nor a Example in .content['application/json'].examples.example-3 for the request body of the **PATCH** endpoint under `/repos/{owner}/{repo}/import`. 
```

This is what the relevant section from the spec looks like:

```yaml
examples:
              example-1:
                summary: Update authentication for an import
                value:
                  vcs_username: octocat
                  vcs_password: secret
              example-2:
                summary: Updating the project choice
                value:
                  vcs: tfvc
                  tfvc_project: project1
                  human_name: project1 (tfs)
              example-3:
                summary: Restarting an import
```

Removing `example-3` from the spec (for testing) leads to the compilation failing without any specific error descriptions:

```
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by mattpolzin** [comment] 2023-08-19 04:47
The aforementioned OpenAPIKit bug should be fixed as of the release I just cut: https://github.com/mattpolzin/OpenAPIKit/releases/tag/3.0.0-beta.1

**Comment by czechboy0** [comment] 2023-08-21 06:53
Thanks @mattpolzin, we're picking that up in https://github.com/apple/swift-openapi-generator/pull/215.

**Comment by czechboy0** [comment] 2023-08-21 10:59
Hi @heikowitte, can you try again with the generator from the main branch? (Just switch `.upToNextMinor(from: "0.1.0")` to `branch: "main"` in your Package.swift). The generator should successfully generate the code, but once you try to build it, I suspect you might still hit #144 - can you confirm, please?

**Comment by czechboy0** [comment] 2023-08-21 12:03
Keeping this marked as likely blocked due to #144.

**Comment by heikowitte** [comment] 2023-08-23 06:45
Yes, it is compiling now, but the resulting code has some issues:

<img width="825" alt="Bildschirmfoto 2023-08-23 um 08 44 37" src="https://github.com/apple/swift-openapi-generator/assets/111968/34dd5cb5-ca37-467b-a6d2-cbd895fae44f">

Not sure if that is relateed to #144 though.

**Comment by czechboy0** [comment] 2023-08-23 06:46
I'll need to see more of the errors to know for sure.

**Comment by czechboy0** [comment] 2023-08-30 14:13
Okay, @heikowitte - I just confirmed that with Swift OpenAPI Generator 0.1.13, the GitHub.com OpenAPI document produces compiling code.

Note that you'll need to enable all these feature flags, e.g. in your openapi-generator-config.yaml, by adding:

featureFlags:
  - proposal0001
  - multipleContentTypes
  - strictOpenAPIValidation
  - closedEnumsAndOneOfs
They will become the default in the upcoming 0.2.0 as well, at which point you won't need to explicitly specify them.

But you should be unblocked now, please file new issues if you find anything else.

**Closed by czechboy0** 2023-08-30 14:13 UTC
Labels: kind/bug
