### ISSUE TITLE
Status Code description 

### ISSUE THREAD

**Issue by miguel-arrf** [apple/swift-openapi-generator#202] opened 2023-08-16 13:04 UTC
Hi! 👋

I'm having a small issue and I want to clarify if this is the expected behaviour, an omission or if it was a design decision 🙂!

So, here's one of my paths:

```yaml
  "/v1/users":
    post:
      tags:
      - v1
      summary: Adds a new user to the database if it doesn't already exist.
      description: |-
        Adds a user to the database.

        Args:
            username (str): ...
            name (str): ...

        Returns:
            JSONResponse: 201 if the user was created successfully.
                          409 if the user already exists.
      operationId: add_user_v1_users_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UserCreateRequest"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '201':
          description: Creates and adds the user successfully.
        '409':
          description: User already exists.
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
``` 

If I go to Postman and I do a request to this endpoint when the return is - for instance - the status code `409`, it will return me, **in the body**, the description:

```yaml
{
    "message": "User already exists."
}
``` 

**However**, if I use the generated Swift client, the case of the response is - as expected - Conflict (status code 409), but I don't have any way of knowing the description.

This is the result: `conflict(ios_client.Operations.add_user_v1_users_post.Output.Conflict(headers: ios_client.Operations.add_user_v1_users_post.Output.Conflict.Headers(), body: nil))`

Now, If I change the specification file to have the following (where I added the content part): 

```
'409':
   description: User already exists.
   content:
      application/json:
         schema: {}
``` 

**Now I have the description as the body of the result.** (instead of it being nil)

Is this the expected behaviour? Should the response always contain the description in the body? Or should I add the `content` section to each one of my responses?

I tried to understand what the [expected behaviour](https://swagger.io/docs/specification/describing-responses/#:~:text=status%20requires%20a-,description,-.%20For%20example%2C%20you) is, but I wasn't able to do so.

Thank you so much for the help!

**Comment by czechboy0** [comment] 2023-08-16 14:09
Hi @miguel-arrf,

I suspect there's some confusion coming from the fact that "User already exists." is both the description of the 409 response, and it's _also_ being returned in JSON as the payload itself. But they're completely separate things.

The reason you're getting `nil` in the generated body is because the response says that there isn't any body documented!

```yaml
'409':
  description: User already exists.
```

As you discovered, you can get access to the body being sent by the user by documenting a body, in your case you did:

```yaml
'409':
  description: User already exists.
  content:
    application/json:
      schema: {}
```

But you could go further and document the structure to give you easier access to the message:

```yaml
'409':
  description: User already exists.
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
        required:
          - message
```

To answer you question - yes, it's expected behavior that no Swift body struct is generated if no body is documented in the OpenAPI document for the response. The generated code only parses what is documented, and ignores anything else.

To be fair though, if the description of the '409' response already is "User already exists.", I don't think you even need to look at the body, since you know what the problem is (you're trying to create another user with the same unique identifier). The status code 409 tells you all you need to know.

Closing the issue, but thanks for the great detail that showed everything necessary to know what is going wrong 🙂

**Closed by czechboy0** 2023-08-16 14:09 UTC
