### ISSUE TITLE
Build of package using swift-openapi-generator fails with "Multiple commands produce ... Types.swift"

### ISSUE THREAD

**Issue by timbms** [apple/swift-openapi-generator#376] opened 2023-11-13 15:31 UTC
Hi,
I want to migrate to swift-openapi-generator. It worked fine when I experimented with the inclusion as demonstrated in the WWDC demo.
Now I want to shift the generator code to the embedded package that is defined via a `Package.swift`:
```
// swift-tools-version:5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "OpenHABCore",
    platforms: [.iOS(.v13), .watchOS(.v7)],
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "OpenHABCore",
            targets: ["OpenHABCore"]
        )
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/Alamofire/Alamofire.git", .upToNextMajor(from: "5.4.4")),
        .package(url: "https://github.com/cezheng/Fuzi.git", .upToNextMajor(from: "3.0.0")),
        .package(url: "https://github.com/onevcat/Kingfisher.git", .upToNextMajor(from: "7.0.0")),
        .package(url: "https://github.com/apple/swift-openapi-runtime", .upToNextMinor(from: "0.3.6")),
        .package(url: "https://github.com/apple/swift-openapi-urlsession", .upToNextMinor(from: "0.3.0")),
        .package(url: "https://github.com/apple/swift-openapi-generator", .upToNextMinor(from: "0.3.4"))
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "OpenHABCore",
            dependencies: [
                .product(name: "Alamofire", package: "Alamofire"),
                .product(name: "Fuzi", package: "Fuzi"),
                .product(name: "Kingfisher", package: "Kingfisher"),
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime"),
                .product(name: "OpenAPIURLSession", package: "swift-openapi-urlsession")
            ],
            plugins: [
                .plugin(name: "OpenAPIGenerator", package: "swift-openapi-generator")
            ]
        ),
        .testTarget(
            name: "OpenHABCoreTests",
            dependencies: ["OpenHABCore"],
            resources: [
                .process("Resources")
            ]
        )
    ]
)
```
Build fails with the following message:

```
Multiple commands produce '/Users/tms/Library/Developer/Xcode/DerivedData/openHAB-ckplhxolppnyfvfzhxhwmsaovpap/SourcePackages/plugins/openhabcore.output/OpenHABCore/OpenAPIGenerator/GeneratedSources/Types.swift'

That command depends on command in Target 'OpenHABCore' (project 'OpenHABCore'): script phase “Running swift-openapi-generator”
That command depends on command in Target 'OpenHABCore' (project 'OpenHABCore'): script phase “Running swift-openapi-generator”
Multiple commands produce '/Users/tms/Library/Developer/Xcode/DerivedData/openHAB-ckplhxolppnyfvfzhxhwmsaovpap/SourcePackages/plugins/openhabcore.output/OpenHABCore/OpenAPIGenerator/GeneratedSources/Client.swift'

Multiple commands produce '/Users/tms/Library/Developer/Xcode/DerivedData/openHAB-ckplhxolppnyfvfzhxhwmsaovpap/SourcePackages/plugins/openhabcore.output/OpenHABCore/OpenAPIGenerator/GeneratedSources/Server.swift'
```
Any help would be very much appreciated. 
Tim

**Comment by luomein** [comment] 2023-11-13 16:15
Try adding swift-http-types dependency.

`let package = Package(
    name: "OpenHABCore",
    platforms: [.iOS(.v13), .watchOS(.v7)],
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "OpenHABCore",
            targets: ["OpenHABCore"]
        )
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/Alamofire/Alamofire.git", .upToNextMajor(from: "5.4.4")),
        .package(url: "https://github.com/cezheng/Fuzi.git", .upToNextMajor(from: "3.0.0")),
        .package(url: "https://github.com/onevcat/Kingfisher.git", .upToNextMajor(from: "7.0.0")),
        .package(url: "https://github.com/apple/swift-openapi-runtime", .upToNextMinor(from: "0.3.6")),
        .package(url: "https://github.com/apple/swift-openapi-urlsession", .upToNextMinor(from: "0.3.0")),
        .package(url: "https://github.com/apple/swift-openapi-generator", .upToNextMinor(from: "0.3.4")),
        .package(url: "https://github.com/apple/swift-http-types", from: "1.0.0"),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "OpenHABCore",
            dependencies: [
                .product(name: "Alamofire", package: "Alamofire"),
                .product(name: "Fuzi", package: "Fuzi"),
                .product(name: "Kingfisher", package: "Kingfisher"),
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime"),
                .product(name: "OpenAPIURLSession", package: "swift-openapi-urlsession"),
                .product(name: "HTTPTypes", package: "swift-http-types"),
            ],
            plugins: [
                .plugin(name: "OpenAPIGenerator", package: "swift-openapi-generator")
            ]
        ),
        .testTarget(
            name: "OpenHABCoreTests",
            dependencies: ["OpenHABCore"],
            resources: [
                .process("Resources")
            ]
        )
    ]
)`

**Comment by luomein** [comment] 2023-11-13 16:18
Try add swift-http-types dependency.

```
let package = Package(
    name: "OpenHABCore",
    platforms: [.iOS(.v13), .watchOS(.v7)],
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "OpenHABCore",
            targets: ["OpenHABCore"]
        )
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/Alamofire/Alamofire.git", .upToNextMajor(from: "5.4.4")),
        .package(url: "https://github.com/cezheng/Fuzi.git", .upToNextMajor(from: "3.0.0")),
        .package(url: "https://github.com/onevcat/Kingfisher.git", .upToNextMajor(from: "7.0.0")),
        .package(url: "https://github.com/apple/swift-openapi-runtime", .upToNextMinor(from: "0.3.6")),
        .package(url: "https://github.com/apple/swift-openapi-urlsession", .upToNextMinor(from: "0.3.0")),
        .package(url: "https://github.com/apple/swift-openapi-generator", .upToNextMinor(from: "0.3.4")),
        .package(url: "https://github.com/apple/swift-http-types", from: "1.0.0"),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "OpenHABCore",
            dependencies: [
                .product(name: "Alamofire", package: "Alamofire"),
                .product(name: "Fuzi", package: "Fuzi"),
                .product(name: "Kingfisher", package: "Kingfisher"),
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime"),
                .product(name: "OpenAPIURLSession", package: "swift-openapi-urlsession"),
                .product(name: "HTTPTypes", package: "swift-http-types"),
            ],
            plugins: [
                .plugin(name: "OpenAPIGenerator", package: "swift-openapi-generator")
            ]
        ),
        .testTarget(
            name: "OpenHABCoreTests",
            dependencies: ["OpenHABCore"],
            resources: [
                .process("Resources")
            ]
        )
    ]
)
```

**Comment by czechboy0** [comment] 2023-11-13 16:23
Hi @timbms,

I don't think @luomein's suggestion will address your issue, you shouldn't have to explicitly depend on swift-http-types.

A few things to check:
1. Did you open the package in Xcode directly, or is this package nested in an Xcode project or workspace? The logs almost suggest that the generator is running twice. But you should _either_ add the plugin in Package.swift, _or_ add it as a Run build plugin phase in the Xcode project, not both.
2. Do you have files that are called Types.swift, Client.swift, or Server.swift in your target? If so, please rename them. Alternatively, you could move the generated code into a dedicated module, and import it from `OpenHABCore`, at which point the duplicate file names wouldn't be an issue. More in https://swiftpackageindex.com/apple/swift-openapi-generator/0.3.4/documentation/swift-openapi-generator/api-stability-of-generated-code#Create-a-curated-client-library-package

**Comment by timbms** [comment] 2023-11-13 17:23
Thanks for the quick support. 

1. The package is nested in a Xcode workspace. The generator plugin is added to the Package.swift only. There is no addition to the Run build plugin phase in the Xcode project. I rechecked for all targets. Still the plugin seems to be run twice.
3. There are no files named Types.swift, Client.swift, Server.swift in the package. Seems there is only the possibility to go via the curated library

I also gave @luomein's idea a try. Without success

**Comment by czechboy0** [comment] 2023-11-13 17:25
If you open the package using `open Package.swift` instead of opening it within your Xcode workspace, does it still fail?

And sure, try with the curated library, it helps separate generated and hand-written code nicely anyway, and hopefully it'll address your issue.

**Comment by kelvinlauKL** [comment] 2023-11-17 01:49
I'm having similar issues:

<img width="896" alt="Screenshot 2023-11-16 at 5 49 29 PM" src="https://github.com/apple/swift-openapi-generator/assets/11384608/89275c10-589d-459c-bd5b-6089b356f8de">

**Comment by kelvinlauKL** [comment] 2023-11-17 01:50
Ah, writing `import HTTPTypes` solved my problem

**Comment by simonjbeaumont** [comment] 2023-11-17 14:30
@kelvinlauKL to your issue

> Ah, writing `import HTTPTypes` solved my problem

Right, you don't have to import `HTTPTypes` if you are simply using the generated client, because the client deals in terms of network agnostic input and output types. But if you start implementing the transport or middleware protocols from the runtime library then you will require `HTTPTypes`.

**Comment by czechboy0** [comment] 2023-11-24 13:06
Hi @timbms, were you able to resolve the issue?

**Comment by czechboy0** [comment] 2023-12-11 09:30
Closing for now, please comment again if this is still reproducing and we can reopen.

**Closed by czechboy0** 2023-12-11 09:30 UTC
Labels: kind/support

**Comment by czechboy0** [comment] 2024-02-29 10:40
Can you provide your Package.swift? So far every time we saw this it was a misconfiguration.

**Comment by AkiraHayakawaJMAS** [comment] 2024-02-29 12:37
@czechboy0 
Thanks for the response.
I have prepared a sample app project.
[SampleApp_issues_376.zip](https://github.com/apple/swift-openapi-generator/files/14447928/SampleApp_issues_376.zip)

It consists of an iOS app, a watchOS app and a library configured with a local Swift Package that uses openapi generator.
Try running SampleApp.xcworkspace with Xcode 15.0 or later and run build with the iOS application build scheme.
You will see that the error reported here is reported by Xcode.
On the other hand, if you remove the MyLibrary reference from the watchOS app target in the sample project, the build will succeed. (although the watchOS app cannot reference MyLibrary)

I think it is probably a problem with Xcode, Swift Package Manager, not with openapi generator, but I think it is very inconvenient at the moment, regardless of the solution.

**Comment by czechboy0** [comment] 2024-02-29 12:59
I see, yes please file an issue using feedbackassistant.apple.com. In the meantime, as a workaround, you could switch to ahead-of-time generation which should hopefully unblock you: https://swiftpackageindex.com/apple/swift-openapi-generator/1.2.1/documentation/swift-openapi-generator/manually-invoking-the-generator-cli

**Comment by timbms** [comment] 2024-08-17 18:48
Has there been any progress on this topic? Just tried it with Xcode 15.4 still same result: I need to manually generate Client.swift and Types.swift because I have a iOS and watchOS target

**Comment by simonjbeaumont** [comment] 2024-08-18 19:30
> Just tried it with Xcode 15.4 still same result

Did you mean Xcode 16 beta 4? If not, worth trying. 

Did you ever file an issue with feedback assistant? If so, could you share the FB number?

**Comment by timbms** [comment] 2024-08-18 20:49
> Did you mean Xcode 16 beta 4? If not, worth trying.

Not enough disk space currently 😏 

> Did you ever file an issue with feedback assistant? If so, could you share the FB number?

Just filed an issue: FB14848806

**Comment by simonjbeaumont** [comment] 2024-08-19 08:42
@AkiraHayakawaJMAS OOI, did you also file a request at feedbackassistant? If so, could you also provide the FB number?

**Comment by zhuscat** [comment] 2025-02-07 08:43
Same problem here

**Comment by czechboy0** [comment] 2025-02-07 08:58
@zhuscat can you verify you don't have hand-written files in your target that match the names Types/Client/Server.swift? If so, that'd cause this issue. Otherwise, if you still reproduce this with the latest Xcode, you'll need to file an issue using feedbackassistant, on Xcode. It's not a bug we can fix in this package.
