### ISSUE TITLE
Discourse openapi.json generate issue

### ISSUE THREAD

**Issue by Kyle-Ye** [apple/swift-openapi-generator#72] opened 2023-06-18 10:18 UTC
## Context

I'd like to migrate my existing [DiscourseKit](https://github.com/Kyle-Ye/DiscourseKit) to use swift-openapi-generator

After I download the latest discourse openapi.json from [discourse_api_docs/openapi.json](https://github.com/discourse/discourse_api_docs/blame/main/openapi.json)

I found its version is v3.1.0 and the plugin just emits an error telling me only 3.0.x is supported.

Then browsing the history of the git repo, I tried to use the latest openapi.json with v3.0.3
from this commit [discourse_api_docs/openapi.json](https://github.com/discourse/discourse_api_docs/tree/e9065be9357541602f79af6cddc2e5413fd5553c)

But the result still gives me an error message saying "The given data was not valid YAML."

Is there anything wrong with the upstream data? Or maybe there is a bug in swift-openapi-generator.

```
Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid YAML.", underlyingError: Optional(Expected `items` value in .content['application/json'].schema.properties.badges for the status code '200' response of the **GET** endpoint under `/admin/badges.json` to be parsable as Mapping but it was not.)))
Swift OpenAPI Generator is running with the following configuration:
- OpenAPI document path: /.../DiscourseKit/Sources/DiscourseKit/openapi.json
- Configuration path: /.../DiscourseKit/Sources/DiscourseKit/openapi-generator-config.yaml
- Generator modes: types, client
- Output file names: Types.swift, Client.swift
- Output directory: /.../DiscourseKit-beyciueljvwcoocpkzbiovgfcson/SourcePackages/plugins/discoursekit.output/DiscourseKit/OpenAPIGenerator/GeneratedSources
- Diagnostics output path: <none - logs to stderr>
- Current directory: /.../DiscourseKit
- Is plugin invocation: true
- Additional imports: <none>
```

## Reproduce code

Minimal reproduce code 👇

[DiscourseKit.zip](https://github.com/apple/swift-openapi-generator/files/11781181/DiscourseKit.zip)

**Comment by czechboy0** [comment] 2023-06-18 11:22
The details seem to be in the error description on the first line:

```
Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid YAML.", underlyingError: Optional(Expected `items` value in .content['application/json'].schema.properties.badges for the status code '200' response of the **GET** endpoint under `/admin/badges.json` to be parsable as Mapping but it was not.)))
```

This error is coming from OpenAPIKit.

**Comment by czechboy0** [comment] 2023-06-18 11:24
I see it, the issue is in the OpenAPI doc for discord. The `items` key expects an object value, but there's an array wrapping that object value. Removing the array should fix it.

Might also be worth pasting the doc into an OpenAPI linter first, in case there are other issues.

**Comment by Kyle-Ye** [comment] 2023-06-18 11:34
> I see it, the issue is in the OpenAPI doc for discourse. The `items` key expects an object value, but there's an array wrapping that object value. Removing the array should fix it.
> 
> Might also be worth pasting the doc into an OpenAPI linter first, in case there are other issues.

Got it. So this should be a upstream issue from [discourse_api_docs](https://github.com/discourse/discourse_api_docs). I see there are many fix after [it](https://github.com/discourse/discourse_api_docs/tree/e9065be9357541602f79af6cddc2e5413fd5553c). But the fix also include upgrading the OpenAPI version from 3.0.3 to 3.1.0 2 years ago.

See [Fix spec errors and update search endpoint](https://github.com/discourse/discourse_api_docs/commit/5e101713b58e92ce7e21ceb894c1a266a0410873)

Hope swift-openapi-generator could support 3.1.x soon.

**Comment by Kyle-Ye** [comment] 2023-06-18 11:36
The discussion of supporting OpenAPI v3.1.0 is via https://github.com/apple/swift-openapi-generator/issues/39.

From https://github.com/apple/swift-openapi-generator/issues/39#issuecomment-1593197056, I see v3.1.x was supported in the history of swift-openapi-generator.

Is there something we can config to reenable this feature?

**Comment by czechboy0** [comment] 2023-06-18 12:59
We have never supported 3.1, but it's certainly planned.

Please comment in #39 about this use case, to make sure we can refer back to this thread. Otherwise, okay to close this issue in the meantime?

**Closed** 2023-06-18 13:56 UTC

**Comment by Kyle-Ye** [comment] 2023-06-19 16:20
Tried discourse openapi 3.1 file with my fork branch https://github.com/Kyle-Ye/swift-openapi-generator/tree/openapi_31x

Still get the "items" issue. I suspect maybe there is something wrong with the underlying `OpenAPIKit` or `Yams`.

**Comment by czechboy0** [comment] 2023-06-19 16:43
Can you try with the YAML file? That seems to have the correct nesting as far as I can see: https://github.com/discourse/discourse_api_docs/blob/main/openapi.yml#L173-L177

**Comment by czechboy0** [comment] 2023-06-19 16:44
The JSON file also seems correct from my reading: https://github.com/discourse/discourse_api_docs/blob/main/openapi.json#L170-L176

What's the exact error you're getting?

**Comment by Kyle-Ye** [comment] 2023-06-19 16:48
I've tried both formats. And they will give me the same error
```
error: -[OpenAPIGeneratorCoreTests.YamsParserOpenAPITest testDiscourseOpenAPI] : failed: caught error: "dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid YAML.", underlyingError: Optional(Expected `items` value in .content['application/json'].schema.properties.form_template_ids for the request body of the **POST** endpoint under `/categories.json` to be parsable as Mapping but it was not.)))"
```

**Comment by Kyle-Ye** [comment] 2023-06-19 17:05
Located the bug to be here https://github.com/mattpolzin/OpenAPIKit/blob/84f6702500fb00476d74420c1a0df64cddd3993e/Sources/OpenAPIKit/Schema%20Object/JSONSchemaContext.swift#L926

If we can't transform the issue(Since the 2 repo are not under the same team), I'll open issue on OpenAPIKit to track this.

```
// Input
{
  "form_template_ids": {
    "items": [],
    "type": "array"
  }
}
```

```swift
items = try container.decodeIfPresent(JSONSchema.self, forKey: .items) // ❌ Throw Error
```

**Comment by Kyle-Ye** [comment] 2023-06-19 17:11
Close and transform the issue to https://github.com/mattpolzin/OpenAPIKit/issues/277

**Comment by czechboy0** [comment] 2023-06-19 18:05
Thanks – as @mattpolzin mentioned on that issue, I think both Swift OpenAPI Generator and OpenAPIKit are doing the right thing, and the OpenAPI doc is not valid. I don't think we should relax the type strictness, we _want_ issues like this to be surfaced and fixed, rather than ignored and spread to more docs through copy-paste.

**Comment by Kyle-Ye** [comment] 2023-06-19 18:16
> Thanks – as @mattpolzin mentioned on that issue, I think both Swift OpenAPI Generator and OpenAPIKit are doing the right thing, and the OpenAPI doc is not valid. I don't think we should relax the type strictness, we _want_ issues like this to be surfaced and fixed, rather than ignored and spread to more docs through copy-paste.

Discourse's openapi doc is generated by https://github.com/rswag/rswag. Maybe this repo is the final right place to report and fix the issue. 😂
